#!/usr/bin/env bash
set -x

MOZ_OBJ_ROOT=$1
topsrcdir=$2

rm -rf ${MOZ_OBJ_ROOT}/dist/rust_bindings \
    ${topsrcdir}/servo/components/style/properties/data.pyc \
    ${topsrcdir}/servo/components/style/properties/build.pyc
